[env.collectors.datadog-checks]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[[envs.default.matrix]]
python = ["2.7", "3.8"]
version = ["10.8.0"]

[envs.default.overrides]
matrix.version.env-vars = "GITLAB_RUNNER_VERSION"
