[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.11"]
version = ["1.17"]

[envs.default.overrides]
matrix.version.env-vars = [
    { key = "FLUENTD_VERSION", value = "1.17.0", if = ["1.17"] },
    { key = "FLUENTD_IMAGE_TAG", value = "v1.17", if = ["1.17"] },
]
