[env.collectors.datadog-checks]
check-types = false
mypy-args = [
  "--py2",
  "--disallow-untyped-defs",
  "--follow-imports",
  "silent",
  "datadog_checks/wmi_check/wmi_check.py",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]

[envs.default]
e2e-env = false
platforms = [
  "windows",
]
