[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["6.2"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "CONFLUENT_VERSION", value = "6.2.0", if = ["6.2"] },
  { key = "CONFLUENT_VERSION_CONNECT", value = "0.5.0-6.2.0", if = ["6.2"] },
  { key = "CONFLUENT_KSQLDB_NAME", value = "ksqldb", if = ["6.2"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"