# Project information
site_name: Agent Integrations
site_description: The home of Agent Integrations developer documentation
site_author: Datadog
site_url: https://datadoghq.dev/integrations-core/

# Repository
repo_name: datadog/integrations-core
repo_url: https://github.com/DataDog/integrations-core
edit_uri: blob/master/docs/developer

# Copyright
copyright: 'Copyright &copy; Datadog, Inc. 2020-present'

# Configuration
docs_dir: docs/developer
site_dir: site
extra_css:
  - assets/css/custom.css
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg

# Customization
extra:
  feature:
    instant: true
    tabs: true
  social:
    - icon: solid/blog
      link: https://www.datadoghq.com/blog/engineering/
    - icon: brands/github-alt
      link: https://github.com/DataDog
    - icon: brands/twitter
      link: https://twitter.com/datadoghq
    - icon: brands/instagram
      link: https://www.instagram.com/datadoghq

# Plugins https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
plugins:
  # Built-in
  - search
  # Extra
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Extensions
markdown_extensions:
  # Built-in
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - mkautodoc
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      provider: github
      user: DataDog
      repo: integrations-core
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Setup: setup.md
  - Testing: testing.md
  - E2E: e2e.md
  - Base Package:
    - About: base/about.md
    - HTTP: base/http.md
    - Databases: base/databases.md
    - API: base/api.md
  - Dev Package:
    - "What's in the box?": ddev/layers.md
    - Configuration: ddev/configuration.md
    - Plugins: ddev/plugins.md
    - Test framework: ddev/test.md
    - CLI: ddev/cli.md
  - Guidelines:
    - Style: guidelines/style.md
    - Pull requests: guidelines/pr.md
  - Meta:
    - Config specs: meta/config_specs.md
    - CI: meta/ci.md
    - CD: meta/cd.md
  - Process:
    - Integration release: process/integration_release.md
    - Agent release: process/agent_release.md
  - FAQ:
    - FAQ: faq/faq.md
