[env.collectors.datadog-checks]

[envs.default]
dependencies = [
  "datadog_checks_tests_helper @ {root:uri}/../datadog_checks_tests_helper",
]
e2e-env = false
platforms = [
  "windows",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]
