[env.collectors.datadog-checks]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[[envs.default.matrix]]
python = ["3.11"]
version = ["1.6.6"]

[envs.default.overrides]
matrix.version.env-vars = "ARGO_ROLLOUT_VERSION"

[envs.bench]