[env.collectors.datadog-checks]
check-types = true
mypy-args = [
    "--explicit-package-bases",
]

[[envs.default.matrix]]
python = ["3.13"]
prefect_version = ["3.6.17"]

[envs.default.overrides]
matrix.python.env-vars = "PYTHON"
matrix.prefect_version.env-vars = "PREFECT_VERSION"

