[env.collectors.datadog-checks]
check-types = true
mypy-args = [
  "src/ddev",
]

[envs.default]
python = "3.11"
e2e-env = false
dependencies = [
  "pyyaml",
  "vcrpy",
]
# TODO: remove this when the old CLI is gone
pre-install-commands = [
  "python -m pip install --disable-pip-version-check {verbosity:flag:-1} -e ../datadog_checks_dev[cli]",
]
