[env]
requires = [
  "datadog-checks-dev",
]

[env.collectors.datadog-checks]
check-types = true
mypy-args = [
  "src/ddev",
]

[envs.default]
python = "3.9"
e2e-env = false
dependencies = [
  "vcrpy",
  "urllib3<2",
]
# TODO: remove this when the old CLI is gone
pre-install-commands = [
  "python -m pip install --disable-pip-version-check {verbosity:flag:-1} -e ../datadog_checks_dev[cli]",
]
