[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["27", "38"]

[envs.default]
dependencies = [
  "requests-mock==1.4.0",
]
e2e-env = false
platforms = [
  "linux",
  "macos",
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
