[env.collectors.datadog-checks]
check-types = false
mypy-args = [
    "--py2",
    "--disallow-untyped-defs",
    "--follow-imports silent",
    "--install-types",
    "--non-interactive",
    "datadog_checks/snmp",
]

[[envs.default.matrix]]
python = ["2.7"]
snmplistener = ["false"]

[[envs.default.matrix]]
python = ["3.11"]
snmplistener = ["false", "true"]

[envs.default.overrides]
matrix.snmplistener.env-vars = "SNMP_LISTENER_ENV"

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"