[env.collectors.datadog-checks]
check-types = false

[[envs.default.matrix]]
python = ["3.12"]
snmplistener = ["false", "true"]

[envs.default.overrides]
matrix.snmplistener.env-vars = "SNMP_LISTENER_ENV"

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"