[build-system]
requires = [
    "hatchling>=0.11.2",
]
build-backend = "hatchling.build"

[project]
name = "datadog-kafka-consumer"
description = "The Kafka Consumer check"
readme = "README.md"
keywords = [
    "datadog",
    "datadog agent",
    "datadog check",
    "kafka_consumer",
]
authors = [
    { name = "Datadog", email = "packages@datadoghq.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: System :: Monitoring",
    "Private :: Do Not Upload",
]
dependencies = [
    "datadog-checks-base>=27.1.0",
]
dynamic = [
    "version",
]

[project.license]
text = "BSD-3-Clause"

[project.optional-dependencies]
deps = [
    "gssapi==1.6.1; python_version < '3.0' and (sys_platform != 'darwin' or platform_machine != 'arm64')",
    "gssapi==1.8.2; python_version > '3.0'",
    "kafka-python==2.0.2",
    "kazoo==2.9.0",
]

[project.urls]
Source = "https://github.com/DataDog/integrations-core"

[tool.hatch.version]
path = "datadog_checks/kafka_consumer/__about__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/datadog_checks",
    "/manifest.json",
]

[tool.hatch.build.targets.wheel]
include = [
    "/datadog_checks/kafka_consumer",
]
dev-mode-dirs = [
    ".",
]
