[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.12"]
version = ["3.5.8", "3.6.2"]
ssl = ["true", "false"]

[envs.default.overrides]
matrix.version.env-vars = "ZK_VERSION"
matrix.ssl.env-vars = "SSL"

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
SSL = "false"