[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]

[envs.default]
e2e-env = false
dependencies = [
  "freezegun==1.5.5",
]

[envs.test-data]
description = """
Make zipfile from online data for local testing
"""
detached = true

[envs.test-data.scripts]
create = "python tests/scripts/download_test_data.py"
