version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:${FLAVOR_VERSION}"
    ports:
      - "${EXTERNAL_PORT}:9092"
      - "${EXTERNAL_JMX_PORT}:9999"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_CREATE_TOPICS: "marvel:2:1,dc:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_OFFSETS_STORAGE: "${CONSUMER_OFFSET_STORAGE}"
      JMX_PORT: "9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
