parameters:
  job_name: ''
  check: ''
  display: ''
  test: true
  test_e2e: true
  benchmark: true
  validate: false

jobs:
- job: '${{ coalesce(parameters.job_name, parameters.check) }}_Linux'
  displayName: '${{ parameters.display }}'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - template: './checkout-code.yml'
  - template: './install-deps.yml'
  - template: './set-up-integrations.yml'
    parameters:
      check: ${{ parameters.check }}

  - ${{ if eq(parameters.validate, 'true') }}:
    - template: './run-validations.yml'

  - ${{ if eq(parameters.test, 'true') }}:
    - script: ddev test --cov --pytest-args="--junitxml=junit/test-results.xml" ${{ parameters.check }}
      displayName: 'Run tests'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)

  - ${{ if eq(parameters.test_e2e, 'true') }}:
    - script: ddev env test --new-env ${{ parameters.check }}
      displayName: 'Run E2E tests'

  - ${{ if eq(parameters.benchmark, 'true') }}:
    - script: ddev test --bench --pytest-args="--junitxml=junit/test-bench-results.xml" ${{ parameters.check }}
      displayName: 'Run benchmarks'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results'
