parameters:
  job_name: ''
  check: ''
  display: ''
  test: true
  test_e2e: true
  ddtrace_flag: ''
  benchmark: true
  latest: false
  validate: false
  validate_changed: ''
  validate_codeowners: false
  repo: 'core'
  ispr: false
  run_py2_tests: true  # Whether or not to run python2 tests.
  run_py3_tests: true  # Whether or not to run python3 tests.
  force_base_package: false
  pip_cache_config: null
  coverage: true
  dd_url: https://app.datadoghq.com

jobs:
- job: '${{ coalesce(parameters.job_name, parameters.check) }}_Linux'
  displayName: '${{ parameters.display }}'
  timeoutInMinutes: 90

  services:
    ${{ if eq(parameters.ddtrace_flag, '--ddtrace') }}:
      dd_agent: dd_agent

  pool:
    vmImage: 'ubuntu-20.04'

  variables:
    ${{ if not(eq(parameters.run_py2_tests, 'true')) }}:
      TOX_SKIP_ENV: py27.*  # Don't run py2 tests
    ${{ if not(eq(parameters.run_py3_tests, 'true')) }}:
      TOX_SKIP_ENV: py3.*  # Don't run py2 tests
    ${{ if eq(parameters.ddtrace_flag, '--ddtrace') }}:
      DD_ENV: ci
      DD_SERVICE: ddev-integrations-${{ parameters.repo }}
      DD_TAGS: "team:agent-integrations,platform:linux,check:${{ parameters.check }}"
      DD_TRACE_ANALYTICS_ENABLED: "true"

  steps:
  - template: './checkout-code.yml'

  - template: './install-deps.yml'
    parameters:
      repo: ${{ parameters.repo }}
      pip_cache_config: ${{ parameters.pip_cache_config }}
      run_py2_tests: ${{ parameters.run_py2_tests }}
      dd_url: ${{ parameters.dd_url }}

  # https://docs.codecov.com/docs/codecov-uploader
  - script: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      mv codecov /user/bin/
    displayName: 'Install Codecov'
      
  - template: './set-up-integrations.yml'
    parameters:
      check: ${{ parameters.check }}

  - ${{ if eq(parameters.validate, 'true') }}:
    - template: './run-validations.yml'
      parameters:
        validate_changed: ${{ parameters.validate_changed }}
        check: ${{ parameters.check }}
        repo: ${{ parameters.repo }}
        ispr: ${{ parameters.ispr }}
        validate_codeowners: ${{ parameters.validate_codeowners }}

  - template: './run-tests.yml'
    parameters:
      test_run: '${{ coalesce(parameters.job_name, parameters.check) }}.linux'
      check: ${{ parameters.check }}
      test: ${{ parameters.test }}
      test_e2e: ${{ parameters.test_e2e }}
      ddtrace_flag: ${{ parameters.ddtrace_flag }}
      benchmark: ${{ parameters.benchmark }}
      latest: ${{ parameters.latest }}
      repo: ${{ parameters.repo }}
      coverage: ${{ parameters.coverage }}
      force_base_package: ${{ parameters.force_base_package }}
