[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.8"]

[envs.default]
e2e-env = false
platforms = [
  "windows",
]

[envs.default.overrides]
matrix.python.scripts = [
  { key = "test", value = "_dd-test tests/legacy", if = ["2.7"] },
]
