[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.12"]
impl = ["legacy", "openmetrics"]

[envs.default.overrides]
matrix.impl.env-vars = [
  { key = "USE_OPENMETRICS", value = "true", if = ["openmetrics"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
