[env.collectors.datadog-checks]

[envs.default]
dependencies = [
  "pika==0.13.0",
]

[[envs.default.matrix]]
python = ["2.7", "38"]
version = ["3.5", "3.6", "3.7", "3.8"]

[envs.default.overrides]
matrix.version.env-vars = "RABBITMQ_VERSION"
