[env.collectors.datadog-checks]
check-types = true
mypy-args = [
  "--explicit-package-bases",
]
mypy-files = [
  "datadog_checks/ibm_spectrum_lsf",
  "tests/",
]

[[envs.default.matrix]]
python = ["3.13"]
