[env.collectors.datadog-checks]
check-types = true
mypy-args = [
  "--install-types",
  "--non-interactive",
  "datadog_checks/ibm_spectrum_lsf",
  "tests/",
]
mypy-deps = [
  "types-mock==0.1.5",
]

[[envs.default.matrix]]
python = ["3.12"]
