[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.8"]
version = ["2.0", "2.2", "2.3", "2.4", "2.5"]

[[envs.default.matrix]]
python = ["2.7", "3.8"]
version = ["1.8", "2.0"]
impl = ["legacy"]

[envs.default.overrides]
matrix.version.env-vars = [
  # EOL 01 Oct 2022
  { key = "HAPROXY_VERSION", value = "1.8.30", if = ["1.8"] },
  # EOL 01 Apr 2024
  { key = "HAPROXY_VERSION", value = "2.0.25", if = ["2.0"] },
  # EOL 01 Apr 2025
  { key = "HAPROXY_VERSION", value = "2.2.19", if = ["2.2"] },
  # EOL 01 Jan 2022
  { key = "HAPROXY_VERSION", value = "2.3.16", if = ["2.3"] },
  # EOL 01 Apr 2026
  { key = "HAPROXY_VERSION", value = "2.4.8", if = ["2.4"] },
  # EOL 01 Jan 2023
  { key = "HAPROXY_VERSION", value = "2.5.0", if = ["2.5"] },
]
matrix.impl.env-vars = [
  { key = "HAPROXY_LEGACY", value = "true", if = ["legacy"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.latest.env-vars]
HAPROXY_VERSION = "latest"
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
