[env.collectors.datadog-checks]
check-types = false
mypy-args = [
    "--py2",
    "--install-types",
    "--non-interactive",
    "datadog_checks/",
    "tests/",
]
mypy-deps = [
  "types-mock==0.1.5",
]

[[envs.default.matrix]]
python = ["3.11"]
