[env.collectors.datadog-checks]
check-types = false
mypy-args = [
    "--py2",
    "--install-types",
    "--non-interactive",
    "datadog_checks/",
    "tests/",
]
mypy-deps = [
    "types-mock==0.1.5",
]

[envs.default]
e2e-env = false

[[envs.default.matrix]]
python = ["2.7", "3.11"]
