[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["3.0"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "CASSANDRA_VERSION", value = "3.0.23", if = ["3.0"] },
]

[envs.default.env-vars]
CONTAINER_PORT = "7199"