[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["3.11", "4.1", "5.0"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "CASSANDRA_VERSION", value = "3.11", if = ["3.11"] },
  { key = "CASSANDRA_VERSION", value = "4.1", if = ["4.1"] },
  { key = "CASSANDRA_VERSION", value = "5.0", if = ["5.0"] },
]

[envs.default.env-vars]
CONTAINER_PORT = "7199"