[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["1.7", "1.8", "1.12", "1.23"]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.default.overrides]
matrix.version.env-vars = [
    # 1.7
    { key = "PGBOUNCER_VERSION", value = "1.7.2", if = ["1.7"] },
    { key = "PGBOUNCER_IMAGE_TAG", value = "pgbouncer_1_7", if = ["1.7"] },
    { key = "POSTGRES_IMAGE_TAG", value = "13.4", if = ["1.7"] },
    # 1.8
    { key = "PGBOUNCER_VERSION", value = "1.8.1", if = ["1.8"] },
    { key = "PGBOUNCER_IMAGE_TAG", value = "pgbouncer_1_8", if = ["1.8"] },
    { key = "POSTGRES_IMAGE_TAG", value = "13.4", if = ["1.8"] },
    # 1.12
    { key = "PGBOUNCER_VERSION", value = "1.12.0", if = ["1.12"] },
    { key = "PGBOUNCER_IMAGE_TAG", value = "1.12.0", if = ["1.12"] },
    { key = "POSTGRES_IMAGE_TAG", value = "13.4", if = ["1.12"] },
    # 1.23
    { key = "PGBOUNCER_VERSION", value = "1.23.1", if = ["1.23"] },
    { key = "PGBOUNCER_IMAGE_TAG", value = "1.23.1", if = ["1.23"] },
    { key = "POSTGRES_IMAGE_TAG", value = "15.5", if = ["1.23"] },
]
