[env.collectors.datadog-checks]
check-types = false


[[envs.default.matrix]]
python = ["3.11"]
version = ["6.7", "7.0"]

[envs.default]
platforms = [
  "linux",
  "macos",
]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "VSPHERE_VERSION", value = "6.7.0", if = ["6.7"] },
  { key = "VSPHERE_VERSION", value = "7.0.2", if = ["7.0"] },
]
