[env.collectors.datadog-checks]
check-types = false
mypy-args = [
  "--py2",
  "--check-untyped-defs",
  "--follow-imports",
  "skip",
  "--install-types",
  "--non-interactive",
  "datadog_checks/",
  "tests/",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]

[[envs.default.matrix]]
python = ["2.7", "3.11"]
protocol = ["tls"]

[envs.default.overrides]
env.IOT_EDGE_CONNSTR.e2e-env = { value = true }
matrix.protocol.env-vars = [
  { key = "IOT_EDGE_E2E_TLS_ENABLED", value = "true", if = ["tls"] },
]

[envs.default.env-vars]
IOT_EDGE_E2E_LIBIOTHSM_STD_URL = "https://github.com/Azure/azure-iotedge/releases/download/1.0.10-rc2/libiothsm-std_1.0.10.rc2-1_ubuntu16.04_amd64.deb"
IOT_EDGE_E2E_IOTEDGE_URL = "https://github.com/Azure/azure-iotedge/releases/download/1.0.10-rc2/iotedge_1.0.10.rc2-1_ubuntu16.04_amd64.deb"
IOT_EDGE_E2E_IMAGE = "mcr.microsoft.com/azureiotedge-agent:1.0.10-rc2"
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.default]
e2e-env = false
