[env.collectors.datadog-checks]
check-types = false

mypy-deps = [
    "types-mock==0.1.5",
]

[[envs.default.matrix]]
python = ["3.12"]
version = ["9.0", "10.0", "11.0"]

[envs.default.overrides]
matrix.version.env-vars = [
    { key = "MARKLOGIC_VERSION", value = "9.0-12", if = ["9.0"] },
    { key = "MARKLOGIC_IMAGE", value = "datadog/docker-library", if = ["9.0"] },
    { key = "MARKLOGIC_TAG", value = "marklogic_9_0_12", if = ["9.0"] },
    { key = "MARKLOGIC_VERSION", value = "10.0-10.2", if = ["10.0"] },
    { key = "MARKLOGIC_IMAGE", value = "marklogicdb/marklogic-db", if = ["10.0"] },
    { key = "MARKLOGIC_TAG", value = "10.0-10.2-centos-1.0.2", if = ["10.0"] },
    { key = "MARKLOGIC_VERSION", value = "11.0.3", if = ["11.0"] },
    { key = "MARKLOGIC_IMAGE", value = "marklogicdb/marklogic-db", if = ["11.0"] },
    { key = "MARKLOGIC_TAG", value = "11.0.3-centos-1.0.2", if = ["11.0"] },
]
