[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["2.11"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "AIRFLOW_VERSION", value = "2.11.0", if = ["2.11"] },
]

[envs.latest.env-vars]
AIRFLOW_VERSION = "latest"
