[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["38"]

[[envs.default.matrix]]
python = ["38"]
setup = ["sandbox"]

[envs.default.overrides]
name."^py3.8$".e2e-env = { value = true }
matrix.setup.e2e-env = { value = true, if = ["sandbox"], env = ["TERADATA_SERVER"] }
matrix.setup.env-vars = [
  { key = "USE_TD_SANDBOX", value = "true", if = ["sandbox"] },
]

[envs.default]
e2e-env = false
dependencies = [
  "teradatasql==17.10.0.12",
]
