[env.collectors.datadog-checks]
check-types = false

mypy-deps = [
  "types-mock==0.1.5",
]

[[envs.default.matrix]]
python = ["3.13"]
version = ["7.1"]

[envs.default.env-vars]
GLUSTER_VERSION = "{matrix:version:7.1}"
