[env.collectors.datadog-checks]
base-package-features = ["deps", "db", "json"]
check-types = false
mypy-args = [
  "--check-untyped-defs",
  "--follow-imports",
  "silent",
  "datadog_checks/mysql/statements.py",
]
mypy-deps = [
  "types-cachetools==0.1.10",
  "types-enum34==1.1.1",
  "types-pymysql==1.1.0.1",
]

[[envs.default.matrix]]
python = ["3.13"]
version = [
  "5.7",  # EOL October 21, 2023
  "8.0.36",  # EOL April, 2026
  "8.4.0",
]

[[envs.default.matrix]]
python = ["3.13"]
version = ["8.0"]
replication = ["group"]

[[envs.default.matrix]]
python = ["3.13"]
flavor = ["mariadb"]
version = [
  "10.5",  # EOL 24 June 2025 (LTS version)
  "10.6",  # EOL 06 July 2026 (LTS version)
  "10.11", # EOL 16 Feb 2028 (LTS version)
  "11.4",  # EOL 29 May 2029 (LTS version)
]

[[envs.default.matrix]]
python = ["3.13"]
flavor = ["percona"]
version = [
  "8.0.42",
  "8.4",
]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "COMPOSE_FILE", value = "mysql8.yaml", if = ["8.0.36"] },
  { key = "COMPOSE_FILE", value = "mysql8.yaml", if = ["8.4.0"] },
]
name."8.0-group".env-vars = [
  { key = "COMPOSE_FILE", value = "mysql8-group.yaml" },
]


[envs.default.env-vars]
COMPOSE_FILE = "{matrix:flavor:mysql}.yaml"
MYSQL_FLAVOR = "{matrix:flavor:mysql}"
MYSQL_REPLICATION = "{matrix:replication:classic}"
MYSQL_VERSION = "{matrix:version}"

[envs.default]
dependencies = [
  "psutil"
]

[envs.latest.env-vars]
COMPOSE_FILE = "mysql8.yaml"
MYSQL_FLAVOR = "mysql"
MYSQL_VERSION = "latest"
