[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]

[envs.default]
dependencies = [
  "datadog_checks_tests_helper @ {root:uri}/../datadog_checks_tests_helper",
]
platforms = [
  "windows",
]
