[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.11"]

[envs.default]
dependencies = [
  "datadog_checks_tests_helper @ {root:uri}/../datadog_checks_tests_helper",
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
