[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.8"]

[envs.default]
platforms = [
  "windows",
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.bench]
