[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
kafka_version = ["3.3"]

[envs.default.overrides]
# See mappings between kafka version and confluent versions here: https://docs.confluent.io/platform/current/installation/versions-interoperability.html
matrix.kafka_version.env-vars = [
  { key = "CONFLUENT_VERSION", value = "7.3.0", if = ["3.3"] },
]

[envs.latest.env-vars]
CONFLUENT_VERSION = "latest"
