[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["27", "38"]
version = ["10.1", "11.1", "12.0"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "VERTICA_VERSION", value = "10.1.1-0", if = ["10.1"] },
  { key = "VERTICA_VERSION", value = "11.1.1-0", if = ["11.1"] },
  { key = "VERTICA_VERSION", value = "12.0.0-0", if = ["12.0"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"