trigger: none

pr:
  branches:
    include:
    - master

parameters:
- name: run_py3_tests
  displayName: Run Python 3 tests
  type: boolean
  default: true
- name: agent_image
  displayName: Agent Docker Image
  type: string
  default: datadog/agent-dev:carlosroman-aml-204-python-3-8-upgrade-py3
- name: agent_windows_image
  displayName: Windows Agent Docker Image
  type: string
  default: datadog/agent-dev:carlosroman-aml-204-python-3-8-upgrade-py3-win-servercore
- name: run_py2_tests
  displayName: Run Python 2 tests
  type: boolean
  default: true
- name: agent_image_py2
  displayName: Agent Docker Image for Python 2
  type: string
  default: datadog/agent:6-rc
- name: agent_windows_image_py2
  displayName: Windows Agent Docker Image for Python 2
  type: string
  default: datadog/agent-dev:master-py2-win-servercore

variables:
  DDEV_E2E_AGENT: ${{ parameters.agent_image }}
  DDEV_E2E_AGENT_PY2: ${{ parameters.agent_image_py2 }}
  DDEV_E2E_AGENT_WIN: ${{ parameters.agent_windows_image }}
  DDEV_E2E_AGENT_WIN_PY2: ${{ parameters.agent_windows_image_py2 }}
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1
  DD_TRACE_AGENT_PORT: 8127

resources:
  containers:
    - container: dd_agent
      image: gcr.io/datadoghq/agent:latest
      ports:
        - 8127:8126
      env:
        DD_API_KEY: $(DD_CI_API_KEY)
        DD_HOSTNAME: "none"
        DD_INSIDE_CI: "true"

jobs:
- template: './templates/test-all-checks.yml'
  parameters:
    agent_image_win: ${{ parameters.agent_windows_image }}
    agent_image_win_py2: ${{ parameters.agent_windows_image_py2 }}
    job_name: Agent
    run_py2_tests: ${{ parameters.run_py2_tests }}
    run_py3_tests: ${{ parameters.run_py3_tests }}
    test_e2e: true
    ddtrace_flag: '--ddtrace'
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
      ispr: false
