trigger:
  branches:
    include:
    - master

pr: none

variables:
  - template: './templates/common-variables.yml'

resources:
  containers:
    - container: dd_agent
      image: gcr.io/datadoghq/agent:latest
      ports:
        - 8127:8126
      env:
        DD_API_KEY: $(DD_CI_API_KEY)
        DD_HOSTNAME: "none"
        DD_INSIDE_CI: "true"

jobs:
- template: './templates/test-all-checks.yml'
  parameters:
    run_py2_tests: false  # Don't run python2 tests on master
    test_e2e: true
    ddtrace_flag: '--ddtrace'
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
      ispr: false
