trigger:
  branches:
    include:
    - master

pr: none

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1

jobs:
- template: './templates/test-all-checks.yml'
  parameters:
    run_py2_tests: false  # Don't run python2 tests on master
    test_e2e: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
      ispr: false
