trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - datadog_checks_base/datadog_checks/*
    - datadog_checks_dev/datadog_checks/dev/*.py

variables:
  - template: './templates/common-variables.yml'

resources:
  containers:
    - ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      - container: dd_agent
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8127:8126
        env:
          DD_API_KEY: $(DD_CI_API_KEY)
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"

jobs:
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Changed
    display: Linux
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      ddtrace_flag: '--ddtrace'
    validate: false
    validate_codeowners: false
    validate_changed: changed
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
    ispr: true

- template: './templates/test-single-windows.yml'
  parameters:
    job_name: Changed
    check: '--changed datadog_checks_base datadog_checks_dev datadog_checks_downloader active_directory aspdotnet disk dns_check dotnetclr exchange_server ibm_mq iis network pdh_check sqlserver tcp_check win32_event_log windows_performance_counters windows_service wmi_check'
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      ddtrace_flag: '--ddtrace'
    validate_changed: changed
    display: Windows
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
    ispr: true
