trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - master
  paths:
    exclude:
    - datadog_checks_base/datadog_checks/*

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1

jobs:
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_0
#    display: Linux_0
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_1
#    display: Linux_1
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_2
#    display: Linux_2
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_3
#    display: Linux_3
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_4
#    display: Linux_4
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_5
#    display: Linux_5
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_6
#    display: Linux_6
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_7
#    display: Linux_7
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_8
#    display: Linux_8
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-linux.yml'
#  parameters:
#    job_name: Changed_9
#    display: Linux_9
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_10
#    display: Windows_10
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_11
#    display: Windows_11
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_12
#    display: Windows_12
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_13
#    display: Windows_13
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_14
#    display: Windows_14
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_15
#    display: Windows_15
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_16
#    display: Windows_16
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_17
#    display: Windows_17
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)
#
#- template: './templates/test-single-windows.yml'
#  parameters:
#    job_name: Changed_18
#    display: Windows_18
#    validate: true
#    pip_cache_config:
#      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
#      restoreKeys: |
#        pip | $(Agent.OS)
#      path: $(PIP_CACHE_DIR)

- template: './templates/test-single-windows.yml'
  parameters:
    job_name: Changed_19
    display: Windows_19
    validate: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
