trigger: none

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - datadog_checks_base/datadog_checks/*
    - datadog_checks_dev/datadog_checks/dev/*.py

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1
  DD_TRACE_AGENT_PORT: 8127

resources:
  containers:
    - ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      - container: dd_agent
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8127:8126
        env:
          DD_API_KEY: $(DD_CI_API_KEY)
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"

jobs:
  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_00
      display: Linux_00
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_01
      display: Linux_01
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_02
      display: Linux_02
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_03
      display: Linux_03
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_04
      display: Linux_04
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_05
      display: Linux_05
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_06
      display: Linux_06
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_07
      display: Linux_07
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_08
      display: Linux_08
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true

  - template: './templates/test-single-linux.yml'
    parameters:
      job_name: Changed_09
      display: Linux_09
      ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
        ddtrace_flag: '--ddtrace'
      validate: false
      validate_codeowners: false
      validate_changed: changed
      pip_cache_config:
        key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
        restoreKeys: |
          pip | $(Agent.OS)
        path: $(PIP_CACHE_DIR)
      ispr: true
