schedules:
 - cron: "0 23 * * 0"
   displayName: Weekly CI (Sunday night UTC)
  always: true
  branches:
    include:
    - master

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1

jobs:
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Weekly Metrics Validation
    display: Linux
    check: 'airflow clickhouse'
    latest_metrics: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
