# Nightly run on the master branch.
# This pipeline tests using the latest released version of `datadog_checks_base` rather than the dev version.

schedules:
- cron: "0 5 * * *"
  displayName: Nightly (5am UTC)
  always: true
  branches:
    include:
    - master

pr: none

trigger: none

variables:
  - template: './templates/common-variables.yml'

resources:
  containers:
    - container: dd_agent
      image: gcr.io/datadoghq/agent:latest
      ports:
        - 8127:8126
      env:
        DD_API_KEY: $(DD_CI_API_KEY)
        DD_HOSTNAME: "none"
        DD_INSIDE_CI: "true"

jobs:
- template: './templates/test-all-checks.yml'
  parameters:
    run_py2_tests: false  # Handled via separate nightly
    ddtrace_flag: '--ddtrace'
    force_base_package: true
    test_e2e: false  # e2e tests run in a docker image so the base package wont be forced
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
