name: Cache shared Python dependencies

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  cache:
    name: Cache Python dependencies for ${{ startsWith(matrix.os, 'windows-') && 'Windows' || startsWith(matrix.os, 'macos-') && 'macOS' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    env:
      PYTHON_VERSION: "3.11"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - name: Check cache
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: ${{ runner.os == 'Windows' && '~\AppData\Local\pip\Cache' || runner.os == 'macOS' && '~/Library/Caches/pip' || '~/.cache/pip' }}
        key: >-
          ${{ format(
            'v01-python-{0}-{1}-{2}-{3}',
            env.pythonLocation,
            hashFiles('datadog_checks_base/pyproject.toml'),
            hashFiles('datadog_checks_dev/pyproject.toml'),
            hashFiles('ddev/pyproject.toml')
          )}}
        lookup-only: true

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |-
        pip install ./ddev
        pip install ./datadog_checks_dev[cli]
        pip install ./datadog_checks_base[deps]
      
    - name: Set up Python 2.7
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install python2 python2-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install python2
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - name: Install dependencies for Python 2.7
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install ./datadog_checks_base[deps] ./datadog_checks_dev

    - name: Cache dependencies
      uses: actions/cache/save@v3
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ runner.os == 'Windows' && '~\AppData\Local\pip\Cache' || runner.os == 'macOS' && '~/Library/Caches/pip' || '~/.cache/pip' }}
        key: ${{ steps.cache.outputs.cache-primary-key }}
