name: Daily Flaky Tests (every 8 hours)

on:
  workflow_dispatch:
  schedule:
  # 4 AM, 12 PM, 8 PM UTC
  - cron: "0 4,12,20 * * *"

jobs:
  cache:
    uses: ./.github/workflows/cache-shared-deps.yml

  test:
    needs:
    - cache

    uses: ./.github/workflows/test-all.yml
    with:
      repo: core

      # Options
      # Because -m starts with a dash,
      # click (the library used to build the CLI) will
      # interpret it as an option, not as an argument.
      # To avoid this, using -- syntax,
      # which tells the command that everything following it
      # should be treated as positional arguments, not options
      pytest-args: '-m flaky'
      context: "flaky-tests"
    secrets: inherit

    permissions:
       # needed for compute-matrix in test-target.yml
       contents: read

  publish-test-results:
    needs:
    - test
    if: success() || failure()
    concurrency:
      group: test-results

    permissions:
      checks: write # Needed for test-results-master
      contents: write # Needed for test-results-master
      pull-requests: write # Needed for test-results-master

    uses: ./.github/workflows/test-results-master.yml
    secrets: inherit
