name: Master

on:
  push:
    branches:
    - master

jobs:
  cache:
    uses: ./.github/workflows/cache-shared-deps.yml

  test:
    needs:
    - cache

    uses: ./.github/workflows/test-all.yml
    with:
      repo: core

      # Options
      standard: true
      # Because -m starts with a dash, 
      # click (the library used to build the CLI) will 
      # interpret it as an option, not as an argument.
      # To avoid this, using -- syntax, 
      # which tells the command that everything following it 
      # should be treated as positional arguments, not options
      pytest-args: '-m "not flaky"'
    secrets: inherit

  publish-test-results:
    
    needs:
    - test

    if: success() || failure()
    concurrency:
      group: test-results

    permissions:
      checks: write
      pull-requests: write
      contents: write

    uses: ./.github/workflows/test-results-master.yml
    secrets: inherit

  submit-traces:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/submit-traces.yml
    secrets: inherit
