name: Nightly minimum base package test

on:
  # Triggering minimum base package tests can be useful outside of the schedule, for instance for PRs
  # that add new integrations or ones that bump the Pydantic dependency in the base package.
  # Until we figure out how best to trigger these automatically we're leaving the door open to easily
  # trigger this manually with the right branch.
  workflow_dispatch:
  schedule:
  # 5 AM UTC
  - cron: "0 5 * * *"

jobs:
  test:
    uses: ./.github/workflows/test-all.yml

    # needed for codecov in test-target.yml, allows the action to get a JWT signed by Github
    permissions:
      id-token: write

    with:
      repo: core

      # Options
      standard: true
      minimum-base-package: true
      test-py2: true
    secrets: inherit
    # needed for codecov in test-target.yml, allows the action to get a JWT signed by Github
    permissions:
      id-token: write

  submit-traces:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/submit-traces.yml
    secrets: inherit
