name: Test results

on:
  workflow_run:
    workflows:
    - PR
    types:
    - completed

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  test-results:
    name: Test results
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      pull-requests: write
      actions: read

      # Only needed for private repositories
      contents: read
      issues: read

    steps:
    - name: Download and extract artifacts
      id: download
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p artifacts && cd artifacts

        artifacts_url=${{ github.event.workflow_run.artifacts_url }}

        gh api --paginate "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
        do
          IFS=$'\t' read name url <<< "$artifact"
          gh api $url > "$name.zip"
          unzip -d "$name" "$name.zip"
        done

        if [ "$(ls -A)" ]; then
          ls
        else
          exit 1
        fi
      continue-on-error: true

    - name: Publish test results
      if: steps.download.outcome == 'success'
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        commit: ${{ github.event.workflow_run.head_sha }}
        event_file: artifacts/github-event/event.json
        event_name: ${{ github.event.workflow_run.event }}
        files: "artifacts/**/*.xml"
