name: Test results for the master branch

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  test-results:
    name: Publish
    runs-on: ubuntu-22.04

    env:
      BADGES_BRANCH: badges
      BADGE_PATH: test-results.svg

    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: "${{ env.BADGES_BRANCH }}"

    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        pattern: test-results-*
        path: test-results
        merge-multiple: true

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@27d65e188ec43221b20d26de30f4892fad91df2f # v2.22.0
      id: test-results
      with:
        files: "test-results/*/*.xml"

    - name: Set badge color
      run: |-
        case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac

    - name: Create badge
      uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8 # v2.0.3
      with:
        label: Tests
        status: "${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests_fail }} failed"
        color: "${{ env.BADGE_COLOR }}"
        path: "${{ env.BADGE_PATH }}"

    - name: Configure Git for GitHub Actions bot
      run: |-
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit if stats have changed
      run: |-
        git add "${{ env.BADGE_PATH }}"
        if git commit -m "Update test results from ${{ github.sha }}"; then
          git push
        else
          echo "Nothing has changed"
        fi
