name: Test Agent with Target

on:
  workflow_dispatch:
    inputs:
      integration:
        required: true
        description: Integration (target) to test, e.g. "apache", "kafka_consumer"
        type: string
      environment:
        required: false
        description: Environment to test, e.g. "py3.13". By default runs all
        default: ""
        type: string
      test-py3:
        required: false
        description: Run Python 3 tests
        default: true
        type: boolean
      agent-image:
        required: false
        description: Agent 7 image
        default: "datadog/agent:7-rc"
        type: string
      test-py2:
        required: false
        description: Run Python 2 tests
        default: true
        type: boolean
      agent-image-py2:
        required: false
        description: Agent 6 image
        default: "datadog/agent:6-rc"
        type: string
      platform:
        required: true
        description: Platform to run tests on
        default: linux
        type: choice
        options:
        - linux
        - windows
        - macos

jobs:
  test:
    uses: ./.github/workflows/test-target.yml
    with:
      repo: core

      job-name: "${{ inputs.integration }}-${{ inputs.platform }}-${{ inputs.environment }}"
      platform: ${{ inputs.platform }}
      runner: ${{ inputs.platform == 'linux' && '["ubuntu-22.04"]' || inputs.platform == 'windows' && '["windows-2022"]' || '["macos-14-large"]' }}

      target: ${{ inputs.integration }}

      # Options
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      target-env: ${{ inputs.environment }}
      context: "test-agent-target"
    secrets: inherit
    permissions:
       # needed for codecov in test-target.yml, allows the action to get a JWT signed by Github
       id-token: write
       # needed for compute-matrix in test-target.yml
       contents: read

  submit-traces:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/submit-traces.yml
    secrets: inherit
